// <auto-generated />
using BarlangWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarlangWebApp.Migrations
{
    [DbContext(typeof(BarlangDbContext))]
    [Migration("20250930064718_sqlite.local_migration_346")]
    partial class sqlitelocal_migration_346
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BarlangWebApp.Models.Barlang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hossz")
                        .HasColumnType("REAL");

                    b.Property<double>("Kiterjedes")
                        .HasColumnType("REAL");

                    b.Property<double>("Magassag")
                        .HasColumnType("REAL");

                    b.Property<double>("Melyseg")
                        .HasColumnType("REAL");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("barlangok");
                });
#pragma warning restore 612, 618
        }
    }
}
